spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/godfray
    username: rose
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          batch_size: 5
        format_sql: true
        # generate_statistics: true
        order_inserts: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
logging:
  level:
    org:
      hibernate:
        type: trace

server:
  port: 8081

